# Generated by Django 5.1.4 on 2025-08-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakuru_tourism_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='attractions_id',
            new_name='attractions',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='rating',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
