# Generated by Django 5.1.4 on 2025-08-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakuru_tourism_app', '0002_rename_attractions_id_rating_attractions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='attractions',
            new_name='attraction',
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
