# Generated by Django 5.1.4 on 2025-08-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakuru_tourism_app', '0003_rename_attractions_rating_attraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
